[versions]
composables-cli = "0.3.0"
kotlin = "2.2.20"
shadow = "8.3.8"

[libraries]

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
