[versions]
# Compose
compose = "1.9.1"
composeHotReload = "1.0.0"

# Kotlin
kotlin = "2.2.21"

{{android_versions}}
[libraries]
{{android_libraries}}
[plugins]
{{android_plugins}}
jetbrains-compose-hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
